// <auto-generated />
using System;
using AppMod.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppMod.Data.Migrations
{
    [DbContext(typeof(AppModDbContext))]
    partial class AppModDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppMod.Data.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("m_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("int")
                        .HasColumnName("m_available");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("m_genre");

                    b.Property<DateTime>("ShowTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("show_time");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("ticket_price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("m_title");

                    b.HasKey("MovieId");

                    b.ToTable("movie_table", (string)null);

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            AvailableTickets = 50,
                            Genre = "Sci-Fi",
                            ShowTime = new DateTime(2025, 1, 15, 19, 30, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 100.00m,
                            Title = "Interstellar"
                        },
                        new
                        {
                            MovieId = 2,
                            AvailableTickets = 38,
                            Genre = "Thriller",
                            ShowTime = new DateTime(2025, 1, 15, 21, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 100.00m,
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 3,
                            AvailableTickets = 25,
                            Genre = "Action",
                            ShowTime = new DateTime(2025, 1, 16, 20, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 120.00m,
                            Title = "The Dark Knight"
                        });
                });

            modelBuilder.Entity("AppMod.Data.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("o_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("m_id");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ordered_at");

                    b.Property<int>("TicketQuantity")
                        .HasColumnType("int")
                        .HasColumnName("no_tickets");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.HasKey("OrderId");

                    b.HasIndex("MovieId");

                    b.ToTable("order_table", (string)null);

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            MovieId = 1,
                            OrderedAt = new DateTime(2025, 1, 10, 10, 15, 0, 0, DateTimeKind.Utc),
                            TicketQuantity = 2,
                            TotalPrice = 200.00m
                        },
                        new
                        {
                            OrderId = 2,
                            MovieId = 2,
                            OrderedAt = new DateTime(2025, 1, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            TicketQuantity = 1,
                            TotalPrice = 100.00m
                        },
                        new
                        {
                            OrderId = 3,
                            MovieId = 3,
                            OrderedAt = new DateTime(2025, 1, 10, 12, 30, 0, 0, DateTimeKind.Utc),
                            TicketQuantity = 4,
                            TotalPrice = 480.00m
                        });
                });

            modelBuilder.Entity("AppMod.Data.Entities.Order", b =>
                {
                    b.HasOne("AppMod.Data.Entities.Movie", "Movie")
                        .WithMany("Orders")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("AppMod.Data.Entities.Movie", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
