// <auto-generated />
using GhcDemo.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GhcDemo.Sql.Migrations
{
    [DbContext(typeof(GhcDemoSqlContext))]
    [Migration("20260520021659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("GhcDemo.Sql.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("m_id");

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("INTEGER")
                        .HasColumnName("m_available");

                    b.HasKey("Id");

                    b.ToTable("movie_table", null, t =>
                        {
                            t.HasCheckConstraint("CK_movie_table_m_available", "m_available >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableTickets = 150
                        },
                        new
                        {
                            Id = 2,
                            AvailableTickets = 4
                        },
                        new
                        {
                            Id = 3,
                            AvailableTickets = 0
                        });
                });

            modelBuilder.Entity("GhcDemo.Sql.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("o_id");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("m_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("TicketCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("no_tickets");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("order_table", null, t =>
                        {
                            t.HasCheckConstraint("CK_order_table_no_tickets", "no_tickets > 0");

                            t.HasCheckConstraint("CK_order_table_price", "price >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            Price = 200m,
                            TicketCount = 2
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 2,
                            Price = 540m,
                            TicketCount = 6
                        });
                });

            modelBuilder.Entity("GhcDemo.Sql.Entities.Order", b =>
                {
                    b.HasOne("GhcDemo.Sql.Entities.Movie", "Movie")
                        .WithMany("Orders")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("GhcDemo.Sql.Entities.Movie", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
