// <auto-generated />
using System;
using GhcDemo.Sql.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GhcDemo.Sql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GhcDemo.Sql.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("customers", (string)null);

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CreatedAtUtc = new DateTime(2025, 1, 6, 15, 30, 0, 0, DateTimeKind.Utc),
                            Email = "taylor.nguyen@example.com",
                            FirstName = "Taylor",
                            LastName = "Nguyen",
                            PhoneNumber = "+1-555-0101"
                        },
                        new
                        {
                            CustomerId = 2,
                            CreatedAtUtc = new DateTime(2025, 1, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jordan.patel@example.com",
                            FirstName = "Jordan",
                            LastName = "Patel",
                            PhoneNumber = "+1-555-0102"
                        });
                });

            modelBuilder.Entity("GhcDemo.Sql.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("LegacyMovieId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("MovieId");

                    b.HasIndex("LegacyMovieId")
                        .IsUnique();

                    b.ToTable("movies", (string)null);

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            AvailableTickets = 120,
                            Language = "English",
                            LegacyMovieId = 1,
                            Title = "Interstellar",
                            UnitPrice = 100m
                        },
                        new
                        {
                            MovieId = 2,
                            AvailableTickets = 75,
                            Language = "Japanese",
                            LegacyMovieId = 2,
                            Title = "Spirited Away",
                            UnitPrice = 90m
                        },
                        new
                        {
                            MovieId = 3,
                            AvailableTickets = 40,
                            Language = "English",
                            LegacyMovieId = 3,
                            Title = "The Dark Knight",
                            UnitPrice = 80m
                        });
                });

            modelBuilder.Entity("GhcDemo.Sql.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("OrderedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("orders", (string)null);

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            OrderNumber = "ORD-20250110-0001",
                            OrderedAtUtc = new DateTime(2025, 1, 10, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Confirmed",
                            TotalAmount = 360m
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 1,
                            OrderNumber = "ORD-20250111-0002",
                            OrderedAtUtc = new DateTime(2025, 1, 11, 18, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Confirmed",
                            TotalAmount = 500m
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 2,
                            OrderNumber = "ORD-20250112-0003",
                            OrderedAtUtc = new DateTime(2025, 1, 12, 19, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            TotalAmount = 160m
                        });
                });

            modelBuilder.Entity("GhcDemo.Sql.Entities.OrderLineItem", b =>
                {
                    b.Property<int>("OrderLineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderLineItemId"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderLineItemId");

                    b.HasIndex("MovieId");

                    b.HasIndex("OrderId", "MovieId")
                        .IsUnique();

                    b.ToTable("order_line_items", (string)null);

                    b.HasData(
                        new
                        {
                            OrderLineItemId = 1,
                            LineTotal = 360m,
                            MovieId = 2,
                            OrderId = 1,
                            Quantity = 4,
                            UnitPrice = 90m
                        },
                        new
                        {
                            OrderLineItemId = 2,
                            LineTotal = 500m,
                            MovieId = 1,
                            OrderId = 2,
                            Quantity = 5,
                            UnitPrice = 100m
                        },
                        new
                        {
                            OrderLineItemId = 3,
                            LineTotal = 160m,
                            MovieId = 3,
                            OrderId = 3,
                            Quantity = 2,
                            UnitPrice = 80m
                        });
                });

            modelBuilder.Entity("GhcDemo.Sql.Entities.Order", b =>
                {
                    b.HasOne("GhcDemo.Sql.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GhcDemo.Sql.Entities.OrderLineItem", b =>
                {
                    b.HasOne("GhcDemo.Sql.Entities.Movie", "Movie")
                        .WithMany("OrderLineItems")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GhcDemo.Sql.Entities.Order", "Order")
                        .WithMany("LineItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GhcDemo.Sql.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GhcDemo.Sql.Entities.Movie", b =>
                {
                    b.Navigation("OrderLineItems");
                });

            modelBuilder.Entity("GhcDemo.Sql.Entities.Order", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
